package kr.openbase.adcsmart.service.jna;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;

/**
 * JNA Wrapper for library <b>libOBPktAnalysis</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LibOBPktAnalysisLibrary extends Library 
{
	public static final String JNA_LIBRARY_NAME = "OBPktAnalysis";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(LibOBPktAnalysisLibrary.JNA_LIBRARY_NAME);
	public static final LibOBPktAnalysisLibrary INSTANCE = (LibOBPktAnalysisLibrary)Native.loadLibrary(LibOBPktAnalysisLibrary.JNA_LIBRARY_NAME, LibOBPktAnalysisLibrary.class);
	
	public static final int RET_CODE_FILE_NOT_EXIST = (int)2;
	public static final int PKT_DIR_CLNT_VIP = (int)1;
	public static final int PKT_DIR_CLNT_REAL = (int)2;
	public static final int PKT_DIR_VIP_CLNT = (int)3;
	public static final int MODEL_CODE_ADCSMART_DEFAULT = (int)1000;
	public static final int PKT_DIR_REAL_CLNT = (int)6;
	public static final int RET_CODE_FILE_FORMAT = (int)3;
	public static final int RET_CODE_PARAMETER = (int)1;
	public static final int RET_CODE_OK = (int)0;
	public static final int PKT_DIR_VIP_REAL = (int)4;
	public static final int PKT_DIR_REAL_VIP = (int)5;
	public static final int PKT_DIR_NA = (int)0;
	
//	public static class STPktResponseTimeInfo extends Structure {
//		/** msec. client<->vip */
//		public int m_iCVAvgTime;
//		/** msec */
//		public int m_iCVMaxTime;
//		/** msec */
//		public int m_iCVMinTime;
//		/** msec. vip<->real */
//		public int m_iVRAvgTime;
//		/** msec */
//		public int m_iVRMaxTime;
//		/** msec */
//		public int m_iVRMinTime;
//		public int m_iCVReqCount;
//		public int m_iCVRespCount;
//		public int m_iVRReqCount;
//		public int m_iVRRespCount;
//		public STPktResponseTimeInfo() {
//			super();
//		}
//		protected List<? > getFieldOrder() {
//			return Arrays.asList("m_iCVAvgTime", "m_iCVMaxTime", "m_iCVMinTime", "m_iVRAvgTime", "m_iVRMaxTime", "m_iVRMinTime", "m_iCVReqCount", "m_iCVRespCount", "m_iVRReqCount", "m_iVRRespCount");
//		}
//		public static class ByReference extends STPktResponseTimeInfo implements Structure.ByReference {
//			
//		};
//		public static class ByValue extends STPktResponseTimeInfo implements Structure.ByValue {
//			
//		};
//	};
//	public static class STPktLossInfoDetail extends Structure {
//		public int m_iIsNextValid;
//		public int m_dwRcvTimeSec;
//		public int m_dwRcvTimeUSec;
//		/** 1:normal, 2:abnormal */
//		public int m_iType;
//		/** --1: client->vip, 2:client->real, 3:vip->client, 4:vip->real, 5: real->vip, 6: real->client */
//		public int m_iDirection;
//		/** C type : char[32] */
//		public byte[] m_szSrcIPAddress = new byte[32];
//		/** C type : char[32] */
//		public byte[] m_szDstIPAddress = new byte[32];
//		/** msec\ub2e8\uc704. */
//		public int m_iTimeDiff;
//		/** C type : char[64] */
//		public byte[] m_szSummary = new byte[64];
//		public int m_dwSeqNo;
//		public int m_dwAckNo;
//		public int m_dwDataLength;
//		/** C type : _STPktLossInfoDetail* */
//		public LibOBPktAnalysisLibrary.STPktLossInfoDetail.ByReference next;
//		public STPktLossInfoDetail() {
//			super();
//		}
//		protected List<? > getFieldOrder() {
//			return Arrays.asList("m_iIsNextValid", "m_dwRcvTimeSec", "m_dwRcvTimeUSec", "m_iType", "m_iDirection", "m_szSrcIPAddress", "m_szDstIPAddress", "m_iTimeDiff", "m_szSummary", "m_dwSeqNo", "m_dwAckNo", "m_dwDataLength", "next");
//		}
//		public static class ByReference extends STPktLossInfoDetail implements Structure.ByReference {
//			
//		};
//		public static class ByValue extends STPktLossInfoDetail implements Structure.ByValue {
//			
//		};
//	};
//	public static class STPktHostInfo extends Structure {
//		public int m_iIsNextValid;
//		/** C type : char[32] */
//		public byte[] m_szIPAddress = new byte[32];
//		/** C type : _STPktHostInfo* */
//		public LibOBPktAnalysisLibrary.STPktHostInfo.ByReference next;
//		public STPktHostInfo() {
//			super();
//		}
//		protected List<? > getFieldOrder() {
//			return Arrays.asList("m_iIsNextValid", "m_szIPAddress", "next");
//		}
//		/**
//		 * @param m_szIPAddress C type : char[32]<br>
//		 * @param next C type : _STPktHostInfo*
//		 */
//		public STPktHostInfo(int m_iIsNextValid, byte m_szIPAddress[], LibOBPktAnalysisLibrary.STPktHostInfo.ByReference next) {
//			super();
//			this.m_iIsNextValid = m_iIsNextValid;
//			if ((m_szIPAddress.length != this.m_szIPAddress.length)) 
//				throw new IllegalArgumentException("Wrong array size !");
//			this.m_szIPAddress = m_szIPAddress;
//			this.next = next;
//		}
//		public static class ByReference extends STPktHostInfo implements Structure.ByReference {
//			
//		};
//		public static class ByValue extends STPktHostInfo implements Structure.ByValue {
//			
//		};
//	};
//	public static class STPktLossInfo extends Structure {
//		public int m_iLossCount;
//		public int m_iDetailInfoCount;
//		/** C type : STPktHostInfo */
//		public LibOBPktAnalysisLibrary.STPktHostInfo m_stClientIPAddress;
//		/** C type : STPktHostInfo */
//		public LibOBPktAnalysisLibrary.STPktHostInfo m_stVSIPAddress;
//		/** C type : STPktHostInfo */
//		public LibOBPktAnalysisLibrary.STPktHostInfo m_stRealIPAddress;
//		public int m_iIsNextValid;
//		/** C type : _STPktLossInfoDetail* */
//		public LibOBPktAnalysisLibrary.STPktLossInfoDetail.ByReference m_pstLossInfo;
//		public STPktLossInfo() {
//			super();
//		}
//		protected List<? > getFieldOrder() {
//			return Arrays.asList("m_iLossCount", "m_iDetailInfoCount", "m_stClientIPAddress", "m_stVSIPAddress", "m_stRealIPAddress", "m_iIsNextValid", "m_pstLossInfo");
//		}
//		/**
//		 * @param m_stClientIPAddress C type : STPktHostInfo<br>
//		 * @param m_stVSIPAddress C type : STPktHostInfo<br>
//		 * @param m_stRealIPAddress C type : STPktHostInfo<br>
//		 * @param m_pstLossInfo C type : _STPktLossInfoDetail*
//		 */
//		public STPktLossInfo(int m_iLossCount, int m_iDetailInfoCount, LibOBPktAnalysisLibrary.STPktHostInfo m_stClientIPAddress, LibOBPktAnalysisLibrary.STPktHostInfo m_stVSIPAddress, LibOBPktAnalysisLibrary.STPktHostInfo m_stRealIPAddress, int m_iIsNextValid, LibOBPktAnalysisLibrary.STPktLossInfoDetail.ByReference m_pstLossInfo) {
//			super();
//			this.m_iLossCount = m_iLossCount;
//			this.m_iDetailInfoCount = m_iDetailInfoCount;
//			this.m_stClientIPAddress = m_stClientIPAddress;
//			this.m_stVSIPAddress = m_stVSIPAddress;
//			this.m_stRealIPAddress = m_stRealIPAddress;
//			this.m_iIsNextValid = m_iIsNextValid;
//			this.m_pstLossInfo = m_pstLossInfo;
//		}
//		public static class ByReference extends STPktLossInfo implements Structure.ByReference {
//			
//		};
//		public static class ByValue extends STPktLossInfo implements Structure.ByValue {
//			
//		};
//	};

	/**
	 * 응답시간을 검사한다.
	 * @param pszFileName
	 * @param pszClientIPAddress
	 * @param pszVIPAddress
	 * @param pstRetInfo
	 * @return
	 */
	public int GetResponseTimeInfo(String pszFileName, String szWFileName, String szClientIPAddress, String szVIPAddress, String szRealIPAddress);
	public int GetPacketLossInfoV2(String szRFileName, String szWFileName, String szClientIPAddress, String szVIPAddress, String szRealIPAddress);
}
