package kr.openbase.adcsmart.service.utility;

public enum OBFaultCheckMsg
{
	CHECK_STATUS                ("MSG_FCHKMSG_DIAGING", "MSG_FCHKMSG_DIAGING", "MSG_FCHKMSG_DIAG_RESULT_NORMAL", "MSG_FCHKMSG_DIAG_RESULT_ABNORMAL", "MSG_FCHKMSG_DIAG_FAIL"),
	HW_POWERSUPPLY_CHECK        ("MSG_FCHKMSG_POWER_SUPPLY_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_POWER_SUPPLY_NORMAL", "MSG_FCHKMSG_POWER_SUPPLY_ABNORMAL", "MSG_FCHKMSG_POWER_SUPPLY_DIAG_FAIL"),
	HW_POWERSUPPLY_INFO         ("", "", "MSG_FCHKMSG_POWER_SUPPLY_INFO_NORMAL", "MSG_FCHKMSG_POWER_SUPPLY_INFO_ABNORMAL", "MSG_FCHKMSG_POWER_SUPPLY_INFO_MISSING"),
	HW_POWERSUPPLY_FIRST_INFO   ("MSG_FCHKMSG_POWER_SUPPLY_STATUS_CHECK", "MSG_FCHKMSG_SNMP_DATA_QUERY", "MSG_FCHKMSG_FIRST_POWER_SUPPLY_NORMAL", "MSG_FCHKMSG_FIRST_POWER_SUPPLY_ABNORMAL", ""),
	HW_POWERSUPPLY_SECOND_INFO  ("MSG_FCHKMSG_POWER_SUPPLY_STATUS_CHECK", "MSG_FCHKMSG_SNMP_DATA_QUERY", "MSG_FCHKMSG_SECOND_POWER_SUPPLY_NORMAL", "MSG_FCHKMSG_SECOND_POWER_SUPPLY_ABNORMAL", ""),
	
	HW_UPTIME_CHECK             ("MSG_FCHKMSG_UPTIME_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_UPTIME_CHECK_SUCCESS", "MSG_FCHKMSG_UPTIME_CHECK_FAIL", "MSG_FCHKMSG_UPTIME_CHECK_ANAL_FAIL"),
	HW_UPTIME_INFO              ("MSG_FCHKMSG_UPTIME_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_UPTIME_INFO", "MSG_FCHKMSG_UPTIME_INFO", ""),
	HW_UPTIME_BOOT_INFO         ("MSG_FCHKMSG_SYSTEM_BOOT_CAUSE_ANALING", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_BOOT_CAUSE_NORMAL", "MSG_FCHKMSG_BOOT_CAUSE_ABNORMAL", "MSG_FCHKMSG_BOOT_CAUSE_ANAL_FAIL"),
	HW_UPTIME_INTERVAL_INFO     ("MSG_FCHKMSG_UPTIME_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_UNIT_TIME_WITHIN_FIVE", "MSG_FCHKMSG_UNIT_TIME_MORETH_FIVE", "MSG_FCHKMSG_UNIT_TIME_ANAL_FAIL"),

	HW_LICENSE_CHECK            ("MSG_FCHKMSG_LICENSE_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_LICENSE_NORMAL", "MSG_FCHKMSG_LICENSE_ABNORMAL", "MSG_FCHKMSG_LICENSE_STATUS_CHECK"),
	HW_LICENSE_TROUGHPUT_CHECK  ("MSG_FCHKMSG_THROUGHPUT_CHECK", "MSG_FCHKMSG_THROUGHPUT_CHECK", "MSG_FCHKMSG_THROUGHPUT_NORMAL", "MSG_FCHKMSG_THROUGHPUT_ABNORMAL", "MSG_FCHKMSG_THROUGHPUT_CHECK_FAIL"),
	HW_LICENSE_TROUGHPUT_INFO   ("MSG_FCHKMSG_THROUGHPUT_CHECK", "MSG_FCHKMSG_THROUGHPUT_CHECK", "MSG_FCHKMSG_THROUGHPUT_NORMAL_STD", "MSG_FCHKMSG_THROUGHPUT_ABNORMAL_STD", "MSG_FCHKMSG_THROUGHPUT_CHECK_FAIL"),
	HW_LICENSE_CONNECTION_CHECK ("MSG_FCHKMSG_CONNECTION_CHECK", "MSG_FCHKMSG_CONNECTION_CHECK", "MSG_FCHKMSG_CONNECTION_NORMAL", "MSG_FCHKMSG_CONNECTION_ABNORMAL", "MSG_FCHKMSG_CONNECTION_CHECK_FAIL"),
	HW_LICENSE_CONNECTION_INFO  ("MSG_FCHKMSG_CONNECTION_CHECK", "MSG_FCHKMSG_CONNECTION_CHECK", "MSG_FCHKMSG_CONNECTION_NORMAL_STD", "MSG_FCHKMSG_CONNECTION_ABNORMAL_STD", "MSG_FCHKMSG_CONNECTION_CHECK_FAIL"),
	
	HW_PORT_CHECK               ("MSG_FCHKMSG_PORT_INTERFACE_INFO_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_INTERFACE_NORMAL", "MSG_FCHKMSG_PORT_INTERFACE_ABNORMAL", "MSG_FCHKMSG_PORT_INTERFACE_ANAL_FAIL"),
	HW_PORT_DUPLEX_STATUS       ("MSG_FCHKMSG_PORT_DUPLEX_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_DUPLEX_NO_STATUS_CHANGE", "MSG_FCHKMSG_PORT_DUPLEX_STATUS_CHANGE_PORT", "MSG_FCHKMSG_PORT_DUPLEX_ANAL_FAIL"),
	HW_PORT_SPEED_CHECK         ("MSG_FCHKMSG_PORT_SPEED_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_SPEED_CHECK_NORMAL", "MSG_FCHKMSG_PORT_SPEED_CHECK_ABNORMAL", "MSG_FCHKMSG_PORT_SPEED_ANAL_FAIL"),
	HW_PORT_DUPLEX_HALF         ("MSG_FCHKMSG_PORT_DUPLEX_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_DUPLEX_HALF_NORMAL", "MSG_FCHKMSG_PORT_DUPLEX_HALF_ABNORMAL", "MSG_FCHKMSG_PORT_DUPLEX_HALF_ANAL_FAIL"),
	HW_PORT_DUPLEX_INFO         ("MSG_FCHKMSG_PORT_DUPLEX_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_DUPLEX_HALF_INFO", "MSG_FCHKMSG_PORT_DUPLEX_HALF_INFO", "MSG_FCHKMSG_PORT_DUPLEX_HALF_INFO"),
	HW_PORT_DUPLEX_HALF_INFO    ("MSG_FCHKMSG_PORT_DUPLEX_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_DUPLEX_MODE_INFO", "MSG_FCHKMSG_PORT_DUPLEX_MODE_INFO", "MSG_FCHKMSG_PORT_DUPLEX_MODE_INFO"),
	HW_PORT_SPEED_INFO          ("MSG_FCHKMSG_PORT_SPEED_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_PORT_SPEED_INFO", "MSG_FCHKMSG_PORT_SPEED_INFO", "MSG_FCHKMSG_PORT_SPEED_INFO"),
	HW_PORT_DROP_CHECK          ("MSG_FCHKMSG_DROP_PACKET_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DROP_NO_PACKET", "MSG_FCHKMSG_DROP_PACKET_TOTAL_COUNT", "MSG_FCHKMSG_DROP_PACKET_ANAL_FAIL"),
	HW_PORT_DROP_INFO           ("MSG_FCHKMSG_DROP_PACKET_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DROP_NO_PACKET", "MSG_FCHKMSG_PORT_NUM_DROP_COUNT", "MSG_FCHKMSG_DROP_PACKET_ANAL_FAIL"),
	HW_PORT_ERROR_CHECK         ("MSG_FCHKMSG_ERR_PACKET_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_ERR_NO_PACKET", "MSG_FCHKMSG_ERR_PACKET_TOTAL_COUNT", "MSG_FCHKMSG_ERR_PACKET_ANAL_FAIL"),
	HW_PORT_ERROR_INFO          ("MSG_FCHKMSG_ERR_PACKET_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_ERR_NO_PACKET", "MSG_FCHKMSG_PORT_NUM_ERR_COUNT", "MSG_FCHKMSG_ERR_PACKET_ANAL_FAIL"),//	HW_PORT_ERROR_CHECK         ("ERROR 패킷 점검중..", "MSG_FCHKMSG_DATA_QUERYING", "ERROR 패킷 없음", "ERROR 패킷 발견. 총 %s개", "ERROR 패킷 점검에 실패했습니다."),
	HW_FAN_NORM_CHECK           ("MSG_FCHKMSG_FAN_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_FAN_STATUS_NORMAL", "MSG_FCHKMSG_FAN_STATUS_ABNORMAL", "MSG_FCHKMSG_FAN_STATUS_ANAL_FAIL"),
	HW_FAN_RPM_CHECK            ("MSG_FCHKMSG_FAN_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_FAN_STATUS_NORMAL", "MSG_FCHKMSG_FAN_STATUS_ABNORMAL_STD", "MSG_FCHKMSG_FAN_STATUS_ANAL_FAIL"),
	HW_FAN_RPM_INFO     	    ("MSG_FCHKMSG_FAN_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_FAN_INFO_NORMAL", "MSG_FCHKMSG_FAN_INFO_NORMAL", "MSG_FCHKMSG_FAN_STATUS_ANAL_FAIL"),

	HW_CPU_CHECK        	    ("MSG_FCHKMSG_CPU_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_CPU_STATUS_NORMAL", "MSG_FCHKMSG_CPU_STATUS_ABNORMAL", "MSG_FCHKMSG_CPU_STATUS_ANAL_FAIL"),
	HW_CPU_INFO 	            ("MSG_FCHKMSG_CPU_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_CPU_INFO_NORMAL", "MSG_FCHKMSG_CPU_INFO_NORMAL", "MSG_FCHKMSG_CPU_STATUS_ANAL_FAIL"),
	HW_MP_CPU_INFO 	            ("MP MSG_FCHKMSG_CPU_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_MP_NORMAL", "MSG_FCHKMSG_MP_NORMAL", "MP MSG_FCHKMSG_CPU_STATUS_ANAL_FAIL"),
	HW_SP_CPU_INFO 	            ("MP MSG_FCHKMSG_CPU_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_SP_NORMAL", "MSG_FCHKMSG_SP_NORMAL", "SP MSG_FCHKMSG_CPU_STATUS_ANAL_FAIL"),
	
	HW_MEMORY_CHECK             ("MSG_FCHKMSG_MEMORY_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_MEMORY_STATUS_NORMAL", "MSG_FCHKMSG_MEMORY_STATUS_ABNORMAL", "MSG_FCHKMSG_MEMORY_STATUS_ANAL_FAIL"),
	HW_MEMORY_FREE_INFO         ("MSG_FCHKMSG_MEMORY_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_MEMORY_FREE", "MSG_FCHKMSG_MEMORY_FREE", "MSG_FCHKMSG_MEMORY_STATUS_ANAL_FAIL"),
	HW_MEMORY_USED_INFO         ("MSG_FCHKMSG_MEMORY_USE_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_MEMORY_USE", "MSG_FCHKMSG_MEMORY_USE", "MSG_FCHKMSG_MEMORY_STATUS_ANAL_FAIL"),
	HW_TEMP_NORM_CHECK   	    ("MSG_FCHKMSG_UNIT_TEMP_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_TEMP_STATUS_NORMAL", "MSG_FCHKMSG_TEMP_STATUS_ABNORMAL", "MSG_FCHKMSG_TEMP_STATUS_ANAL_FAIL"),
	HW_TEMP_GAUGE_CHECK 	    ("MSG_FCHKMSG_UNIT_TEMP_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_TEMP_INFO_NORMAL", "MSG_FCHKMSG_TEMP_INFO_ABNORMAL", "MSG_FCHKMSG_TEMP_STATUS_ANAL_FAIL"),
	HW_TEMP_NORM_INFO           ("MSG_FCHKMSG_UNIT_TEMP_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_UNIT_TEMP_NORMAL", "MSG_FCHKMSG_UNIT_TEMP_ABNORMAL", "MSG_FCHKMSG_UNIT_TEMP_ANAL_FAIL"),
	HW_TEMP_GAUGE_INFO          ("MSG_FCHKMSG_UNIT_TEMP_STATUS_CHECK", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_UNIT_TEMP", "MSG_FCHKMSG_UNIT_TEMP", "MSG_FCHKMSG_TEMP_STATUS_ANAL_FAIL"),
	HW_ADCLOG_CHECK 		    ("MSG_FCHKMSG_ADC_LOG_QUERY", "MSG_FCHKMSG_DB_QUERY", "MSG_FCHKMSG_ADC_LAST_LOG_COUNT", "MSG_FCHKMSG_ADC_LAST_LOG_EMPTY", "MSG_FCHKMSG_ADC_LAST_LOG_ANAL_FAIL"),
	HW_OS_CHECK 		        ("MSG_FCHKMSG_OS_INFO_QUERY", "MSG_FCHKMSG_DB_QUERY", "MSG_FCHKMSG_OS_INFO", "MSG_FCHKMSG_OS_INFO", "MSG_FCHKMSG_OS_INFO_ANAL_FAIL"),
	HW_OS_INFO  		        ("MSG_FCHKMSG_OS_INFO_QUERY", "MSG_FCHKMSG_DB_QUERY", "MSG_FCHKMSG_OS_INFO_MODEL", "MSG_FCHKMSG_OS_INFO_MODEL", "MSG_FCHKMSG_OS_INFO_ANAL_FAIL"),

	L23_VLAN_CHECK              ("MSG_FCHKMSG_VLAN_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_VLAN_INFO", "MSG_FCHKMSG_VLAN_INFO_EMPTY", "MSG_FCHKMSG_VLAN_INFO_ANAL_FAIL"),
	L23_INTERFACE_CHECK         ("MSG_FCHKMSG_VLAN_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_INTERFACE_INFO", "MSG_FCHKMSG_INTERFACE_INFO", "MSG_FCHKMSG_INTERFACE_INFO_ANAL_FAIL"),
	L23_STP_CHECK               ("MSG_FCHKMSG_STP_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_STP_INFO", "MSG_FCHKMSG_STP_INFO_ANAL_FAIL", "MSG_FCHKMSG_STP_INFO_EMPTY"),
	L23_TRUNK_CHECK             ("MSG_FCHKMSG_TRUNK_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_TRUNK_INFO", "MSG_FCHKMSG_TRUNK_INFO_EMPTY", "MSG_FCHKMSG_TRUNK_INFO_ANAL_FAIL"),
	L23_LINK_CHECK              ("MSG_FCHKMSG_LINK_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_LINK_INFO", "MSG_FCHKMSG_LINK_INFO_EMPTY", "MSG_FCHKMSG_LINK_INFO_ANAL_FAIL"),
	L23_FAILOVER_CHECK          ("MSG_FCHKMSG_FAILOVER_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_ADC_FAILOVER_STATUS", "MSG_FCHKMSG_ADC_FAILOVER_STATUS", "MSG_FCHKMSG_ADC_FAILOVER_STATUS_ANAL_FAIL"),
	L23_VRRP_CHECK              ("MSG_FCHKMSG_VRRP_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_VRRP_INFO", "MSG_FCHKMSG_VRRP_INFO_EMPTY", "MSG_FCHKMSG_VRRP_INFO_ANAL_FAIL"),
	L23_ARP_CHECK               ("MSG_FCHKMSG_ARP_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_ARP_INFO", "MSG_FCHKMSG_ARP_INFO_EMPTY", "MSG_FCHKMSG_ARP_INFO_ANAL_FAIL"),
	L23_ROUTING_CHECK           ("MSG_FCHKMSG_ROUTING_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_ROUTING_INFO", "MSG_FCHKMSG_ROUTING_INFO_EMPTY", "MSG_FCHKMSG_ROUTING_INFO_ANAL_FAIL"),
	L23_MAC_FLAPPING_CHECK      ("MSG_FCHKMSG_MAC_FLAPPING_ANAL", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_MAC_FLAPPING_ANAL_NORMAL", "MSG_FCHKMSG_MAC_FLAPPING_ANAL_ABNORMAL", "MSG_FCHKMSG_MAC_FLAPPING_ANAL_FAIL"),

	L47_UNUSED_SLB_CHECK        ("MSG_FCHKMSG_NOT_USE_SLB_INFO_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_NOT_USE_SLB_COUNT", "MSG_FCHKMSG_NOT_USE_SLB_EMPTY", "MSG_FCHKMSG_NOT_USE_SLB_ANAL_FAIL"),
	L47_UNUSED_NODE_CHECK       ("MSG_FCHKMSG_NOT_USE_RSERVER_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_NOT_USE_RSERVER_COUNT", "MSG_FCHKMSG_NOT_USE_RSERVER_EMPTY", "MSG_FCHKMSG_NOT_USE_RSERVER_ANAL_FAIL"),
	L47_UNUSED_POOL_CHECK       ("MSG_FCHKMSG_NOT_USE_GROUP_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_NOT_USE_GROUP_COUNT", "MSG_FCHKMSG_NOT_USE_GROUP_EMPTY", "MSG_FCHKMSG_NOT_USE_GROUP_ANAL_FAIL"),
	L47_NOMEMBER_POOOL_CHECK    ("MSG_FCHKMSG_RSERVER_NOT_GROUP_QEURY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_RSERVER_NOT_GROUP_COUNT", "MSG_FCHKMSG_RSERVER_NOT_GRUOP_EMPTY", "MSG_FCHKMSG_RSERVER_NOT_GRUOP_ANAL_FAIL"),
	L47_NOMEMBER_VSERVER_CHECK  ("MSG_FCHKMSG_GROUP_NOT_VS_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_GROUP_NOT_VS_COUNT", "MSG_FCHKMSG_GROUP_NOT_VS_EMPTY", "MSG_FCHKMSG_GROUP_NOT_VS_ANAL_FAIL"),

	L47_SLEEP_NODE_CHECK        ("MSG_FCHKMSG_IDLE_RSERVER_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DAY_NOT_USE_RSERVER_COUNT", "MSG_FCHKMSG_DAY_NOT_USE_RSERVER_EMPTY", "MSG_FCHKMSG_DAY_NOT_USE_RSERVER_ANAL_FAIL"),
	L47_SLEEP_POOL_CHECK        ("MSG_FCHKMSG_IDLE_GROUP_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DAY_NOT_USE_GROUP_COUNT", "MSG_FCHKMSG_DAY_NOT_USE_GROUP_EMPTY", "MSG_FCHKMSG_DAY_NOT_USE_GROUP_ANAL_FAIL"),
	L47_SLEEP_FLB_NODE_CHECK    ("MSG_FCHKMSG_IDLE_RSERVER_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DAY_NOT_USE_FLB_RSERVER_COUNT", "MSG_FCHKMSG_DAY_NOT_USE_FLB_RSERVER_EMPTY", "MSG_FCHKMSG_DAY_NOT_USE_FLB_RSERVER_ANAL_FAIL"),
	L47_SLEEP_FLB_POOL_CHECK    ("MSG_FCHKMSG_IDLE_GROUP_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DAY_NOT_USE_FLB_GROUP_COUNT", "MSG_FCHKMSG_DAY_NOT_USE_FLB_GROUP_EMPTY", "MSG_FCHKMSG_DAY_NOT_USE_FLB_GROUP_ANAL_FAIL"),
	L47_SLEEP_VSERVER_CHECK     ("MSG_FCHKMSG_IDLE_VS_QUERY", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_DAY_NOT_USE_VS_COUNT", "MSG_FCHKMSG_DAY_NOT_USE_VS_EMPTY", "MSG_FCHKMSG_DAY_NOT_USE_VS_ANAL_FAIL"),
	L47_ALLOCATION_FAILURE_CHECK("MSG_FCHKMSG_ALLOCATION_DIAGING", "MSG_FCHKMSG_DATA_QUERYING", "MSG_FCHKMSG_ALLOCATION_NORMAL_OPER", "MSG_FCHKMSG_ALLOCATION_OPER_PROBLEM", "MSG_FCHKMSG_ALLOCATION_DIAG_FAIL"),
	L47_VIP_PKTS_DROP_CHECK     ("MSG_FCHKMSG_VIP_PKTS_ING", "MSG_FCHKMSG_VIP_PKTS_ING", "MSG_FCHKMSG_VIP_PKTS_SUCCESS", "MSG_FCHKMSG_VIP_PKTS_FAIL", "MSG_FCHKMSG_VIP_PKTS_ANAL_FAIL"),
	L47_AUX_TABLE_CHECK         ("MSG_FCHKMSG_AUX_TABLE_ING", "MSG_FCHKMSG_AUX_TABLE_ING", "MSG_FCHKMSG_AUX_TABLE_SUCCESS", "MSG_FCHKMSG_AUX_TABLE_SUCCESS", "MSG_FCHKMSG_AUX_TABLE_ANAL_FAIL"),

//	SVC_ANALYSIS_STATUS         ("서MSG_FCHKMSG_SERVICE_DIAGING", "서비스 진단중입니다.", "서비스는 정상적으로 운영중입니다.", "서비스 운영에 문제가 있습니다.", "서비스 진단에 실패했습니다."),
	SVC_DUMP_PCAP_INFO   	    ("MSG_FCHKMSG_PACKET_COLL", "MSG_FCHKMSG_PACKET_COLL", "MSG_FCHKMSG_PACKET_COLL_SUCCESS", "MSG_FCHKMSG_PACKET_COLL_FAIL", "MSG_FCHKMSG_PACKET_COLL_ANAL_FAIL"),
	SVC_DUMP_PCAP_CHECK 		("MSG_FCHKMSG_PACKET_COLL", "MSG_FCHKMSG_PACKET_COLL", "MSG_FCHKMSG_PACKET_COLL_CHK_SUCCESS", "MSG_FCHKMSG_PACKET_COLL_CHK_FAIL", "MSG_FCHKMSG_PACKET_COLL_CHK_ANAL_FAIL"),
	SVC_DOWNLOAD_PCAP_STATUS    ("MSG_FCHKMSG_PACKET_SENDING", "MSG_FCHKMSG_PACKET_SENDING", "MSG_FCHKMSG_PACKET_DOWNLOAD_SUCCESS", "MSG_FCHKMSG_PACKET_DOWNLOAD_FAIL", "MSG_FCHKMSG_PACKET_DOWNLOAD_ANAL_FAIL"),
	SVC_RESPONSE_TIME_STATUS    ("MSG_FCHKMSG_SERVICE_PERF_ANAL", "MSG_FCHKMSG_SERVICE_PERF_AVG", "MSG_FCHKMSG_SERVICE_PERF_AVG", "MSG_FCHKMSG_SERVICE_PERF_ANAL_FAIL", "MSG_FCHKMSG_SERVICE_PERF_ANAL_FAIL"),
	SVC_RESPONSE_TIME_INFO      ("MSG_FCHKMSG_SVC_RESP_TIME_INFO_ING", "MSG_FCHKMSG_SVC_RESP_TIME_INFO_ING", "MSG_FCHKMSG_SVC_RESP_TIME_INFO_SUCCESS", "MSG_FCHKMSG_SVC_RESP_TIME_INFO_FAIL", "MSG_FCHKMSG_SVC_RESP_TIME_INFO_ANAL_FAIL"),
//	SVC_LOAD_BALANCING_STATUS   ("서비스별 로드밸런싱 분석중입니다. ", "서비스별 로드밸런싱 분석중입니다.", "서비스별 로드밸런싱에 이상 없습니다. ", "서비스별 로드밸런싱에 이상이 있습니다.", "서비스별 로드밸런싱 분석에 실패했습니다."),
	SVC_PACKET_LOSS_CHECK       ("MSG_FCHKMSG_PACKET_ANAL", "MSG_FCHKMSG_PACKET_ANAL", "MSG_FCHKMSG_PACKET_ANAL_NO_LOSS", "MSG_FCHKMSG_PACKET_ANAL_LOSS", "MSG_FCHKMSG_PACKET_ANAL_FAIL"),
	SVC_PACKET_LOSS_INFO        ("", "", "MSG_FCHKMSG_ALL_PACKET_COUNT", "MSG_FCHKMSG_ALL_PACKET_COUNT", ""),
//	SVC_ANALYSIS_DISABLE_STATUS ("서비스 진단은 진행하지 않습니다.", "서비스 진단은 진행하지 않습니다.", "서비스 진단은 진행하지 않습니다.", "서비스 진단은 진행하지 않습니다.", "서비스 진단은 진행하지 않습니다."),

	SNMP_QUERY_CHECK        	("MSG_FCHKMSG_SNMP_DATA_QUERY", "MSG_FCHKMSG_SNMP_DATA_QUERY", "MSG_FCHKMSG_SNMP_DATA_QUERY_SUCCESS", "MSG_FCHKMSG_SNMP_DATA_QUERY_FAIL", "MSG_FCHKMSG_SNMP_DATA_QUERY_FAIL"),
	SNMP_QUERY     				("MSG_FCHKMSG_SNMP_DATA_QUERY", "MSG_FCHKMSG_SNMP_QUERY_ING", "MSG_FCHKMSG_SNMP_QUERY_SUCCESS", "MSG_FCHKMSG_SNMP_QUERY_FAIL", ""),
	SNMP_QUERY_VALUE 			("MSG_FCHKMSG_SNMP_DATA_QUERY", "MSG_FCHKMSG_SNMP_QUERY_ING", "MSG_FCHKMSG_SNMP_QUERY_VALUE_SUCCESS", "MSG_FCHKMSG_SNMP_QUERY_VALUE_FAIL", ""),
	
//	CONNECTING_STATUS ("장비 접속중입니다.", "장비 접속중입니다.", "장비 접속에 성공했습니다.", "장비 접속에 실패했습니다.", ""),
	
	PACKET_NO_DATA     			("", "", "MSG_FCHKMSG_COLL_NO_PACKET", "MSG_FCHKMSG_COLL_NO_PACKET", "MSG_FCHKMSG_COLL_NO_PACKET"),
	DB_QUERY     				("MSG_FCHKMSG_DB_QUERY", "MSG_FCHKMSG_DB_QUERY", "MSG_FCHKMSG_DB_QUERY_SUCCESS", "MSG_FCHKMSG_DB_QUERY_FAIL", "MSG_FCHKMSG_DB_QUERY_FAIL"),
	DATA_NOT_EXIST 				("", "", "MSG_FCHKMSG_NO_DATA", "MSG_FCHKMSG_NO_DATA", ""),
	DROP_PKT_EXIST 				("", "", "MSG_FCHKMSG_PACKET_DROP_OCCUR", "MSG_FCHKMSG_PACKET_DROP_OCCUR", ""),
	PARSE_PACKET 				("MSG_FCHKMSG_PACKET_ANAL", "MSG_FCHKMSG_PACKET_ANAL", "MSG_FCHKMSG_PACKET_ANAL_SUCCESS", "MSG_FCHKMSG_PACKET_ANAL_FAIL", "MSG_FCHKMSG_PACKET_ANAL_FAIL"),
	PARSE_DATA     				("", "", "MSG_FCHKMSG_DATA_PARSHING_SUCCESS", "MSG_FCHKMSG_DATA_PARSHING_FAIL", "MSG_FCHKMSG_DATA_PARSHING_FAIL"),
	PARSE_DATA_VALUE    		("", "", "MSG_FCHKMSG_DATA_PARSHING_SUCCESS", "MSG_FCHKMSG_DATA_PARSHING_FAIL_DATA", "MSG_FCHKMSG_DATA_PARSHING_FAIL"),
	TELNET_QUERY   				("MSG_FCHKMSG_TELNET_DATA_QUERY", "MSG_FCHKMSG_TELNET_DATA_QUERY", "MSG_FCHKMSG_TELNET_DATA_QUERY_SUCCESS", "MSG_FCHKMSG_TELNET_DATA_QUERY_FAIL", ""),
	SSH_QUERY			    	("MSG_FCHKMSG_SSH_DATA_QUERY", "MSG_FCHKMSG_SSH_DATA_QUERY ", "MSG_FCHKMSG_SSH_DATA_QUERY_SUCCESS", "MSG_FCHKMSG_SSH_DATA_QUERY_FAIL", ""),
//	CHECK_FAULT    				("MSG_FCHKMSG_FAIL_ANAL", "MSG_FCHKMSG_FAIL_ANAL", "MSG_FCHKMSG_FAIL_ANAL_SUCCESS", "MSG_FCHKMSG_FAIL_ANAL_FAIL", ""),
	INVALID_PARAMETER 			("MSG_FCHKMSG_INPUT_PARA_ABNORMAL", "MSG_FCHKMSG_INPUT_PARA_ABNORMAL", "MSG_FCHKMSG_INPUT_PARA_ABNORMAL", "MSG_FCHKMSG_INPUT_PARA_ABNORMAL", "MSG_FCHKMSG_INPUT_PARA_ABNORMAL"),
	NOT_SUPPORT    				("MSG_FCHKMSG_NOT_SUPPORT_FUNC", "MSG_FCHKMSG_NOT_SUPPORT_FUNC", "MSG_FCHKMSG_NOT_SUPPORT_FUNC", "MSG_FCHKMSG_NOT_SUPPORT_FUNC", "MSG_FCHKMSG_NOT_SUPPORT_FUNC");  
	
	private String itemMsg;
	private String actionMsg;
	private String successMsg;
	private String failMsg;
	private String processFailMsg;
	
	OBFaultCheckMsg(String itemMsg, String actionMsg, String succMsg, String failMsg, String extraMsg)
	{
		this.itemMsg = itemMsg;
		this.actionMsg = actionMsg;
		this.successMsg = succMsg;
		this.failMsg = failMsg;
		this.processFailMsg = extraMsg;
	}
	public String getProcessFailMsg()
	{
		return OBMessages.getMessage(processFailMsg);
	}
	public String getSuccessMsg()
	{
		return OBMessages.getMessage(successMsg);
	}
	public String getFailMsg()
	{
		return OBMessages.getMessage(failMsg);
	}
	public String getItemMsg()
	{
		return OBMessages.getMessage(itemMsg);
	}
	public String getActionMsg()
	{
		return OBMessages.getMessage(actionMsg);
	}
}
